import { Meta, Story } from '@storybook/react/types-6-0';
import type { CashtabBadgeProps } from './CashtabBadge';
export declare const Standard: Story<CashtabBadgeProps>;
export declare const MostProps: Story<CashtabBadgeProps>;
export declare const Minimal: Story<CashtabBadgeProps>;
export declare const Fiat: Story<CashtabBadgeProps>;
export declare const BCHA: Story<CashtabBadgeProps>;
export declare const SLPA: Story<CashtabBadgeProps>;
export declare const StepControlled: Story<CashtabBadgeProps>;
declare const _default: Meta<import("@storybook/react/types-6-0").Args>;
export default _default;
